
package cn.com.cig.adsense.dao.wsdl.yipai;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "YjkForAdvertizement", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://app.easypass.cn/yijike/api/YjkForAdvertizement.asmx?WSDL")
public class YjkForAdvertizement
    extends Service
{

    private final static URL YJKFORADVERTIZEMENT_WSDL_LOCATION;
    private final static WebServiceException YJKFORADVERTIZEMENT_EXCEPTION;
    private final static QName YJKFORADVERTIZEMENT_QNAME = new QName("http://tempuri.org/", "YjkForAdvertizement");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://app.easypass.cn/yijike/api/YjkForAdvertizement.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        YJKFORADVERTIZEMENT_WSDL_LOCATION = url;
        YJKFORADVERTIZEMENT_EXCEPTION = e;
    }

    public YjkForAdvertizement() {
        super(__getWsdlLocation(), YJKFORADVERTIZEMENT_QNAME);
    }

    public YjkForAdvertizement(WebServiceFeature... features) {
        super(__getWsdlLocation(), YJKFORADVERTIZEMENT_QNAME, features);
    }

    public YjkForAdvertizement(URL wsdlLocation) {
        super(wsdlLocation, YJKFORADVERTIZEMENT_QNAME);
    }

    public YjkForAdvertizement(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, YJKFORADVERTIZEMENT_QNAME, features);
    }

    public YjkForAdvertizement(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public YjkForAdvertizement(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns YjkForAdvertizementSoap
     */
    @WebEndpoint(name = "YjkForAdvertizementSoap")
    public YjkForAdvertizementSoap getYjkForAdvertizementSoap() {
        return super.getPort(new QName("http://tempuri.org/", "YjkForAdvertizementSoap"), YjkForAdvertizementSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns YjkForAdvertizementSoap
     */
    @WebEndpoint(name = "YjkForAdvertizementSoap")
    public YjkForAdvertizementSoap getYjkForAdvertizementSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "YjkForAdvertizementSoap"), YjkForAdvertizementSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (YJKFORADVERTIZEMENT_EXCEPTION!= null) {
            throw YJKFORADVERTIZEMENT_EXCEPTION;
        }
        return YJKFORADVERTIZEMENT_WSDL_LOCATION;
    }

}
