// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserBehavior.proto

package cn.com.cig.adsense.vo.fix;

public final class UserBehavior {
  private UserBehavior() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MaterialBehaviorListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .cn.com.cig.adsense.protobuf.MaterialBehavior materialBehavior = 1;
    /**
     * <code>repeated .cn.com.cig.adsense.protobuf.MaterialBehavior materialBehavior = 1;</code>
     */
    java.util.List<cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior> 
        getMaterialBehaviorList();
    /**
     * <code>repeated .cn.com.cig.adsense.protobuf.MaterialBehavior materialBehavior = 1;</code>
     */
    cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior getMaterialBehavior(int index);
    /**
     * <code>repeated .cn.com.cig.adsense.protobuf.MaterialBehavior materialBehavior = 1;</code>
     */
    int getMaterialBehaviorCount();
    /**
     * <code>repeated .cn.com.cig.adsense.protobuf.MaterialBehavior materialBehavior = 1;</code>
     */
    java.util.List<? extends cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorOrBuilder> 
        getMaterialBehaviorOrBuilderList();
    /**
     * <code>repeated .cn.com.cig.adsense.protobuf.MaterialBehavior materialBehavior = 1;</code>
     */
    cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorOrBuilder getMaterialBehaviorOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code cn.com.cig.adsense.protobuf.MaterialBehaviorList}
   */
  public static final class MaterialBehaviorList extends
      com.google.protobuf.GeneratedMessage
      implements MaterialBehaviorListOrBuilder {
    // Use MaterialBehaviorList.newBuilder() to construct.
    private MaterialBehaviorList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MaterialBehaviorList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MaterialBehaviorList defaultInstance;
    public static MaterialBehaviorList getDefaultInstance() {
      return defaultInstance;
    }

    public MaterialBehaviorList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MaterialBehaviorList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                materialBehavior_ = new java.util.ArrayList<cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior>();
                mutable_bitField0_ |= 0x00000001;
              }
              materialBehavior_.add(input.readMessage(cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          materialBehavior_ = java.util.Collections.unmodifiableList(materialBehavior_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.com.cig.adsense.vo.fix.UserBehavior.internal_static_cn_com_cig_adsense_protobuf_MaterialBehaviorList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.com.cig.adsense.vo.fix.UserBehavior.internal_static_cn_com_cig_adsense_protobuf_MaterialBehaviorList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorList.class, cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorList.Builder.class);
    }

    public static com.google.protobuf.Parser<MaterialBehaviorList> PARSER =
        new com.google.protobuf.AbstractParser<MaterialBehaviorList>() {
      public MaterialBehaviorList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MaterialBehaviorList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MaterialBehaviorList> getParserForType() {
      return PARSER;
    }

    // repeated .cn.com.cig.adsense.protobuf.MaterialBehavior materialBehavior = 1;
    public static final int MATERIALBEHAVIOR_FIELD_NUMBER = 1;
    private java.util.List<cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior> materialBehavior_;
    /**
     * <code>repeated .cn.com.cig.adsense.protobuf.MaterialBehavior materialBehavior = 1;</code>
     */
    public java.util.List<cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior> getMaterialBehaviorList() {
      return materialBehavior_;
    }
    /**
     * <code>repeated .cn.com.cig.adsense.protobuf.MaterialBehavior materialBehavior = 1;</code>
     */
    public java.util.List<? extends cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorOrBuilder> 
        getMaterialBehaviorOrBuilderList() {
      return materialBehavior_;
    }
    /**
     * <code>repeated .cn.com.cig.adsense.protobuf.MaterialBehavior materialBehavior = 1;</code>
     */
    public int getMaterialBehaviorCount() {
      return materialBehavior_.size();
    }
    /**
     * <code>repeated .cn.com.cig.adsense.protobuf.MaterialBehavior materialBehavior = 1;</code>
     */
    public cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior getMaterialBehavior(int index) {
      return materialBehavior_.get(index);
    }
    /**
     * <code>repeated .cn.com.cig.adsense.protobuf.MaterialBehavior materialBehavior = 1;</code>
     */
    public cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorOrBuilder getMaterialBehaviorOrBuilder(
        int index) {
      return materialBehavior_.get(index);
    }

    private void initFields() {
      materialBehavior_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < materialBehavior_.size(); i++) {
        output.writeMessage(1, materialBehavior_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < materialBehavior_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, materialBehavior_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.com.cig.adsense.protobuf.MaterialBehaviorList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.com.cig.adsense.vo.fix.UserBehavior.internal_static_cn_com_cig_adsense_protobuf_MaterialBehaviorList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.com.cig.adsense.vo.fix.UserBehavior.internal_static_cn_com_cig_adsense_protobuf_MaterialBehaviorList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorList.class, cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorList.Builder.class);
      }

      // Construct using cn.com.cig.adsense.vo.UserBehavior.MaterialBehaviorList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMaterialBehaviorFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (materialBehaviorBuilder_ == null) {
          materialBehavior_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          materialBehaviorBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.com.cig.adsense.vo.fix.UserBehavior.internal_static_cn_com_cig_adsense_protobuf_MaterialBehaviorList_descriptor;
      }

      public cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorList getDefaultInstanceForType() {
        return cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorList.getDefaultInstance();
      }

      public cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorList build() {
        cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @SuppressWarnings("unused")
	public cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorList buildPartial() {
        cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorList result = new cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorList(this);
        int from_bitField0_ = bitField0_;
        if (materialBehaviorBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            materialBehavior_ = java.util.Collections.unmodifiableList(materialBehavior_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.materialBehavior_ = materialBehavior_;
        } else {
          result.materialBehavior_ = materialBehaviorBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorList) {
          return mergeFrom((cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorList other) {
        if (other == cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorList.getDefaultInstance()) return this;
        if (materialBehaviorBuilder_ == null) {
          if (!other.materialBehavior_.isEmpty()) {
            if (materialBehavior_.isEmpty()) {
              materialBehavior_ = other.materialBehavior_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMaterialBehaviorIsMutable();
              materialBehavior_.addAll(other.materialBehavior_);
            }
            onChanged();
          }
        } else {
          if (!other.materialBehavior_.isEmpty()) {
            if (materialBehaviorBuilder_.isEmpty()) {
              materialBehaviorBuilder_.dispose();
              materialBehaviorBuilder_ = null;
              materialBehavior_ = other.materialBehavior_;
              bitField0_ = (bitField0_ & ~0x00000001);
              materialBehaviorBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMaterialBehaviorFieldBuilder() : null;
            } else {
              materialBehaviorBuilder_.addAllMessages(other.materialBehavior_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .cn.com.cig.adsense.protobuf.MaterialBehavior materialBehavior = 1;
      private java.util.List<cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior> materialBehavior_ =
        java.util.Collections.emptyList();
      private void ensureMaterialBehaviorIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          materialBehavior_ = new java.util.ArrayList<cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior>(materialBehavior_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior, cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior.Builder, cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorOrBuilder> materialBehaviorBuilder_;

      /**
       * <code>repeated .cn.com.cig.adsense.protobuf.MaterialBehavior materialBehavior = 1;</code>
       */
      public java.util.List<cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior> getMaterialBehaviorList() {
        if (materialBehaviorBuilder_ == null) {
          return java.util.Collections.unmodifiableList(materialBehavior_);
        } else {
          return materialBehaviorBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .cn.com.cig.adsense.protobuf.MaterialBehavior materialBehavior = 1;</code>
       */
      public int getMaterialBehaviorCount() {
        if (materialBehaviorBuilder_ == null) {
          return materialBehavior_.size();
        } else {
          return materialBehaviorBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .cn.com.cig.adsense.protobuf.MaterialBehavior materialBehavior = 1;</code>
       */
      public cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior getMaterialBehavior(int index) {
        if (materialBehaviorBuilder_ == null) {
          return materialBehavior_.get(index);
        } else {
          return materialBehaviorBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .cn.com.cig.adsense.protobuf.MaterialBehavior materialBehavior = 1;</code>
       */
      public Builder setMaterialBehavior(
          int index, cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior value) {
        if (materialBehaviorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMaterialBehaviorIsMutable();
          materialBehavior_.set(index, value);
          onChanged();
        } else {
          materialBehaviorBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cn.com.cig.adsense.protobuf.MaterialBehavior materialBehavior = 1;</code>
       */
      public Builder setMaterialBehavior(
          int index, cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior.Builder builderForValue) {
        if (materialBehaviorBuilder_ == null) {
          ensureMaterialBehaviorIsMutable();
          materialBehavior_.set(index, builderForValue.build());
          onChanged();
        } else {
          materialBehaviorBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cn.com.cig.adsense.protobuf.MaterialBehavior materialBehavior = 1;</code>
       */
      public Builder addMaterialBehavior(cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior value) {
        if (materialBehaviorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMaterialBehaviorIsMutable();
          materialBehavior_.add(value);
          onChanged();
        } else {
          materialBehaviorBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .cn.com.cig.adsense.protobuf.MaterialBehavior materialBehavior = 1;</code>
       */
      public Builder addMaterialBehavior(
          int index, cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior value) {
        if (materialBehaviorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMaterialBehaviorIsMutable();
          materialBehavior_.add(index, value);
          onChanged();
        } else {
          materialBehaviorBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cn.com.cig.adsense.protobuf.MaterialBehavior materialBehavior = 1;</code>
       */
      public Builder addMaterialBehavior(
          cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior.Builder builderForValue) {
        if (materialBehaviorBuilder_ == null) {
          ensureMaterialBehaviorIsMutable();
          materialBehavior_.add(builderForValue.build());
          onChanged();
        } else {
          materialBehaviorBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cn.com.cig.adsense.protobuf.MaterialBehavior materialBehavior = 1;</code>
       */
      public Builder addMaterialBehavior(
          int index, cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior.Builder builderForValue) {
        if (materialBehaviorBuilder_ == null) {
          ensureMaterialBehaviorIsMutable();
          materialBehavior_.add(index, builderForValue.build());
          onChanged();
        } else {
          materialBehaviorBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cn.com.cig.adsense.protobuf.MaterialBehavior materialBehavior = 1;</code>
       */
      public Builder addAllMaterialBehavior(
          java.lang.Iterable<? extends cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior> values) {
        if (materialBehaviorBuilder_ == null) {
          ensureMaterialBehaviorIsMutable();
          super.addAll(values, materialBehavior_);
          onChanged();
        } else {
          materialBehaviorBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .cn.com.cig.adsense.protobuf.MaterialBehavior materialBehavior = 1;</code>
       */
      public Builder clearMaterialBehavior() {
        if (materialBehaviorBuilder_ == null) {
          materialBehavior_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          materialBehaviorBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .cn.com.cig.adsense.protobuf.MaterialBehavior materialBehavior = 1;</code>
       */
      public Builder removeMaterialBehavior(int index) {
        if (materialBehaviorBuilder_ == null) {
          ensureMaterialBehaviorIsMutable();
          materialBehavior_.remove(index);
          onChanged();
        } else {
          materialBehaviorBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .cn.com.cig.adsense.protobuf.MaterialBehavior materialBehavior = 1;</code>
       */
      public cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior.Builder getMaterialBehaviorBuilder(
          int index) {
        return getMaterialBehaviorFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .cn.com.cig.adsense.protobuf.MaterialBehavior materialBehavior = 1;</code>
       */
      public cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorOrBuilder getMaterialBehaviorOrBuilder(
          int index) {
        if (materialBehaviorBuilder_ == null) {
          return materialBehavior_.get(index);  } else {
          return materialBehaviorBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .cn.com.cig.adsense.protobuf.MaterialBehavior materialBehavior = 1;</code>
       */
      public java.util.List<? extends cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorOrBuilder> 
           getMaterialBehaviorOrBuilderList() {
        if (materialBehaviorBuilder_ != null) {
          return materialBehaviorBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(materialBehavior_);
        }
      }
      /**
       * <code>repeated .cn.com.cig.adsense.protobuf.MaterialBehavior materialBehavior = 1;</code>
       */
      public cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior.Builder addMaterialBehaviorBuilder() {
        return getMaterialBehaviorFieldBuilder().addBuilder(
            cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior.getDefaultInstance());
      }
      /**
       * <code>repeated .cn.com.cig.adsense.protobuf.MaterialBehavior materialBehavior = 1;</code>
       */
      public cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior.Builder addMaterialBehaviorBuilder(
          int index) {
        return getMaterialBehaviorFieldBuilder().addBuilder(
            index, cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior.getDefaultInstance());
      }
      /**
       * <code>repeated .cn.com.cig.adsense.protobuf.MaterialBehavior materialBehavior = 1;</code>
       */
      public java.util.List<cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior.Builder> 
           getMaterialBehaviorBuilderList() {
        return getMaterialBehaviorFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior, cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior.Builder, cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorOrBuilder> 
          getMaterialBehaviorFieldBuilder() {
        if (materialBehaviorBuilder_ == null) {
          materialBehaviorBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior, cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior.Builder, cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorOrBuilder>(
                  materialBehavior_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          materialBehavior_ = null;
        }
        return materialBehaviorBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:cn.com.cig.adsense.protobuf.MaterialBehaviorList)
    }

    static {
      defaultInstance = new MaterialBehaviorList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:cn.com.cig.adsense.protobuf.MaterialBehaviorList)
  }

  public interface MaterialBehaviorOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string materialId = 1;
    /**
     * <code>optional string materialId = 1;</code>
     */
    boolean hasMaterialId();
    /**
     * <code>optional string materialId = 1;</code>
     */
    java.lang.String getMaterialId();
    /**
     * <code>optional string materialId = 1;</code>
     */
    com.google.protobuf.ByteString
        getMaterialIdBytes();

    // optional int32 impressionPeriod = 2;
    /**
     * <code>optional int32 impressionPeriod = 2;</code>
     */
    boolean hasImpressionPeriod();
    /**
     * <code>optional int32 impressionPeriod = 2;</code>
     */
    int getImpressionPeriod();

    // optional int32 clickPeriod = 3;
    /**
     * <code>optional int32 clickPeriod = 3;</code>
     */
    boolean hasClickPeriod();
    /**
     * <code>optional int32 clickPeriod = 3;</code>
     */
    int getClickPeriod();

    // optional int64 lastImpression = 4;
    /**
     * <code>optional int64 lastImpression = 4;</code>
     */
    boolean hasLastImpression();
    /**
     * <code>optional int64 lastImpression = 4;</code>
     */
    long getLastImpression();

    // optional int64 lastClick = 5;
    /**
     * <code>optional int64 lastClick = 5;</code>
     */
    boolean hasLastClick();
    /**
     * <code>optional int64 lastClick = 5;</code>
     */
    long getLastClick();

    // optional string productId = 6;
    /**
     * <code>optional string productId = 6;</code>
     */
    boolean hasProductId();
    /**
     * <code>optional string productId = 6;</code>
     */
    java.lang.String getProductId();
    /**
     * <code>optional string productId = 6;</code>
     */
    com.google.protobuf.ByteString
        getProductIdBytes();

    // optional string modelId = 7;
    /**
     * <code>optional string modelId = 7;</code>
     */
    boolean hasModelId();
    /**
     * <code>optional string modelId = 7;</code>
     */
    java.lang.String getModelId();
    /**
     * <code>optional string modelId = 7;</code>
     */
    com.google.protobuf.ByteString
        getModelIdBytes();
  }
  /**
   * Protobuf type {@code cn.com.cig.adsense.protobuf.MaterialBehavior}
   */
  public static final class MaterialBehavior extends
      com.google.protobuf.GeneratedMessage
      implements MaterialBehaviorOrBuilder {
    // Use MaterialBehavior.newBuilder() to construct.
    private MaterialBehavior(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MaterialBehavior(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MaterialBehavior defaultInstance;
    public static MaterialBehavior getDefaultInstance() {
      return defaultInstance;
    }

    public MaterialBehavior getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    @SuppressWarnings("unused")
	private MaterialBehavior(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              materialId_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              impressionPeriod_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              clickPeriod_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              lastImpression_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              lastClick_ = input.readInt64();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              productId_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              modelId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.com.cig.adsense.vo.fix.UserBehavior.internal_static_cn_com_cig_adsense_protobuf_MaterialBehavior_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.com.cig.adsense.vo.fix.UserBehavior.internal_static_cn_com_cig_adsense_protobuf_MaterialBehavior_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior.class, cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior.Builder.class);
    }

    public static com.google.protobuf.Parser<MaterialBehavior> PARSER =
        new com.google.protobuf.AbstractParser<MaterialBehavior>() {
      public MaterialBehavior parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MaterialBehavior(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MaterialBehavior> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string materialId = 1;
    public static final int MATERIALID_FIELD_NUMBER = 1;
    private java.lang.Object materialId_;
    /**
     * <code>optional string materialId = 1;</code>
     */
    public boolean hasMaterialId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string materialId = 1;</code>
     */
    public java.lang.String getMaterialId() {
      java.lang.Object ref = materialId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          materialId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string materialId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMaterialIdBytes() {
      java.lang.Object ref = materialId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        materialId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 impressionPeriod = 2;
    public static final int IMPRESSIONPERIOD_FIELD_NUMBER = 2;
    private int impressionPeriod_;
    /**
     * <code>optional int32 impressionPeriod = 2;</code>
     */
    public boolean hasImpressionPeriod() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 impressionPeriod = 2;</code>
     */
    public int getImpressionPeriod() {
      return impressionPeriod_;
    }

    // optional int32 clickPeriod = 3;
    public static final int CLICKPERIOD_FIELD_NUMBER = 3;
    private int clickPeriod_;
    /**
     * <code>optional int32 clickPeriod = 3;</code>
     */
    public boolean hasClickPeriod() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 clickPeriod = 3;</code>
     */
    public int getClickPeriod() {
      return clickPeriod_;
    }

    // optional int64 lastImpression = 4;
    public static final int LASTIMPRESSION_FIELD_NUMBER = 4;
    private long lastImpression_;
    /**
     * <code>optional int64 lastImpression = 4;</code>
     */
    public boolean hasLastImpression() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 lastImpression = 4;</code>
     */
    public long getLastImpression() {
      return lastImpression_;
    }

    // optional int64 lastClick = 5;
    public static final int LASTCLICK_FIELD_NUMBER = 5;
    private long lastClick_;
    /**
     * <code>optional int64 lastClick = 5;</code>
     */
    public boolean hasLastClick() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 lastClick = 5;</code>
     */
    public long getLastClick() {
      return lastClick_;
    }

    // optional string productId = 6;
    public static final int PRODUCTID_FIELD_NUMBER = 6;
    private java.lang.Object productId_;
    /**
     * <code>optional string productId = 6;</code>
     */
    public boolean hasProductId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string productId = 6;</code>
     */
    public java.lang.String getProductId() {
      java.lang.Object ref = productId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          productId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string productId = 6;</code>
     */
    public com.google.protobuf.ByteString
        getProductIdBytes() {
      java.lang.Object ref = productId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string modelId = 7;
    public static final int MODELID_FIELD_NUMBER = 7;
    private java.lang.Object modelId_;
    /**
     * <code>optional string modelId = 7;</code>
     */
    public boolean hasModelId() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string modelId = 7;</code>
     */
    public java.lang.String getModelId() {
      java.lang.Object ref = modelId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          modelId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string modelId = 7;</code>
     */
    public com.google.protobuf.ByteString
        getModelIdBytes() {
      java.lang.Object ref = modelId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      materialId_ = "";
      impressionPeriod_ = 0;
      clickPeriod_ = 0;
      lastImpression_ = 0L;
      lastClick_ = 0L;
      productId_ = "";
      modelId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMaterialIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, impressionPeriod_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, clickPeriod_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, lastImpression_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, lastClick_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getProductIdBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getModelIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMaterialIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, impressionPeriod_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, clickPeriod_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, lastImpression_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, lastClick_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getProductIdBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getModelIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.com.cig.adsense.protobuf.MaterialBehavior}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehaviorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.com.cig.adsense.vo.fix.UserBehavior.internal_static_cn_com_cig_adsense_protobuf_MaterialBehavior_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.com.cig.adsense.vo.fix.UserBehavior.internal_static_cn_com_cig_adsense_protobuf_MaterialBehavior_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior.class, cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior.Builder.class);
      }

      // Construct using cn.com.cig.adsense.vo.UserBehavior.MaterialBehavior.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        materialId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        impressionPeriod_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        clickPeriod_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        lastImpression_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        lastClick_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        productId_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        modelId_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.com.cig.adsense.vo.fix.UserBehavior.internal_static_cn_com_cig_adsense_protobuf_MaterialBehavior_descriptor;
      }

      public cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior getDefaultInstanceForType() {
        return cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior.getDefaultInstance();
      }

      public cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior build() {
        cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior buildPartial() {
        cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior result = new cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.materialId_ = materialId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.impressionPeriod_ = impressionPeriod_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.clickPeriod_ = clickPeriod_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.lastImpression_ = lastImpression_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.lastClick_ = lastClick_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.productId_ = productId_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.modelId_ = modelId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior) {
          return mergeFrom((cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior other) {
        if (other == cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior.getDefaultInstance()) return this;
        if (other.hasMaterialId()) {
          bitField0_ |= 0x00000001;
          materialId_ = other.materialId_;
          onChanged();
        }
        if (other.hasImpressionPeriod()) {
          setImpressionPeriod(other.getImpressionPeriod());
        }
        if (other.hasClickPeriod()) {
          setClickPeriod(other.getClickPeriod());
        }
        if (other.hasLastImpression()) {
          setLastImpression(other.getLastImpression());
        }
        if (other.hasLastClick()) {
          setLastClick(other.getLastClick());
        }
        if (other.hasProductId()) {
          bitField0_ |= 0x00000020;
          productId_ = other.productId_;
          onChanged();
        }
        if (other.hasModelId()) {
          bitField0_ |= 0x00000040;
          modelId_ = other.modelId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.com.cig.adsense.vo.fix.UserBehavior.MaterialBehavior) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string materialId = 1;
      private java.lang.Object materialId_ = "";
      /**
       * <code>optional string materialId = 1;</code>
       */
      public boolean hasMaterialId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string materialId = 1;</code>
       */
      public java.lang.String getMaterialId() {
        java.lang.Object ref = materialId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          materialId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string materialId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMaterialIdBytes() {
        java.lang.Object ref = materialId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          materialId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string materialId = 1;</code>
       */
      public Builder setMaterialId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        materialId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string materialId = 1;</code>
       */
      public Builder clearMaterialId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        materialId_ = getDefaultInstance().getMaterialId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string materialId = 1;</code>
       */
      public Builder setMaterialIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        materialId_ = value;
        onChanged();
        return this;
      }

      // optional int32 impressionPeriod = 2;
      private int impressionPeriod_ ;
      /**
       * <code>optional int32 impressionPeriod = 2;</code>
       */
      public boolean hasImpressionPeriod() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 impressionPeriod = 2;</code>
       */
      public int getImpressionPeriod() {
        return impressionPeriod_;
      }
      /**
       * <code>optional int32 impressionPeriod = 2;</code>
       */
      public Builder setImpressionPeriod(int value) {
        bitField0_ |= 0x00000002;
        impressionPeriod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 impressionPeriod = 2;</code>
       */
      public Builder clearImpressionPeriod() {
        bitField0_ = (bitField0_ & ~0x00000002);
        impressionPeriod_ = 0;
        onChanged();
        return this;
      }

      // optional int32 clickPeriod = 3;
      private int clickPeriod_ ;
      /**
       * <code>optional int32 clickPeriod = 3;</code>
       */
      public boolean hasClickPeriod() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 clickPeriod = 3;</code>
       */
      public int getClickPeriod() {
        return clickPeriod_;
      }
      /**
       * <code>optional int32 clickPeriod = 3;</code>
       */
      public Builder setClickPeriod(int value) {
        bitField0_ |= 0x00000004;
        clickPeriod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 clickPeriod = 3;</code>
       */
      public Builder clearClickPeriod() {
        bitField0_ = (bitField0_ & ~0x00000004);
        clickPeriod_ = 0;
        onChanged();
        return this;
      }

      // optional int64 lastImpression = 4;
      private long lastImpression_ ;
      /**
       * <code>optional int64 lastImpression = 4;</code>
       */
      public boolean hasLastImpression() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 lastImpression = 4;</code>
       */
      public long getLastImpression() {
        return lastImpression_;
      }
      /**
       * <code>optional int64 lastImpression = 4;</code>
       */
      public Builder setLastImpression(long value) {
        bitField0_ |= 0x00000008;
        lastImpression_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 lastImpression = 4;</code>
       */
      public Builder clearLastImpression() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lastImpression_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 lastClick = 5;
      private long lastClick_ ;
      /**
       * <code>optional int64 lastClick = 5;</code>
       */
      public boolean hasLastClick() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 lastClick = 5;</code>
       */
      public long getLastClick() {
        return lastClick_;
      }
      /**
       * <code>optional int64 lastClick = 5;</code>
       */
      public Builder setLastClick(long value) {
        bitField0_ |= 0x00000010;
        lastClick_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 lastClick = 5;</code>
       */
      public Builder clearLastClick() {
        bitField0_ = (bitField0_ & ~0x00000010);
        lastClick_ = 0L;
        onChanged();
        return this;
      }

      // optional string productId = 6;
      private java.lang.Object productId_ = "";
      /**
       * <code>optional string productId = 6;</code>
       */
      public boolean hasProductId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string productId = 6;</code>
       */
      public java.lang.String getProductId() {
        java.lang.Object ref = productId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          productId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string productId = 6;</code>
       */
      public com.google.protobuf.ByteString
          getProductIdBytes() {
        java.lang.Object ref = productId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string productId = 6;</code>
       */
      public Builder setProductId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        productId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string productId = 6;</code>
       */
      public Builder clearProductId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        productId_ = getDefaultInstance().getProductId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string productId = 6;</code>
       */
      public Builder setProductIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        productId_ = value;
        onChanged();
        return this;
      }

      // optional string modelId = 7;
      private java.lang.Object modelId_ = "";
      /**
       * <code>optional string modelId = 7;</code>
       */
      public boolean hasModelId() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string modelId = 7;</code>
       */
      public java.lang.String getModelId() {
        java.lang.Object ref = modelId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          modelId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string modelId = 7;</code>
       */
      public com.google.protobuf.ByteString
          getModelIdBytes() {
        java.lang.Object ref = modelId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          modelId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string modelId = 7;</code>
       */
      public Builder setModelId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        modelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string modelId = 7;</code>
       */
      public Builder clearModelId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        modelId_ = getDefaultInstance().getModelId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string modelId = 7;</code>
       */
      public Builder setModelIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        modelId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:cn.com.cig.adsense.protobuf.MaterialBehavior)
    }

    static {
      defaultInstance = new MaterialBehavior(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:cn.com.cig.adsense.protobuf.MaterialBehavior)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_com_cig_adsense_protobuf_MaterialBehaviorList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cn_com_cig_adsense_protobuf_MaterialBehaviorList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_com_cig_adsense_protobuf_MaterialBehavior_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cn_com_cig_adsense_protobuf_MaterialBehavior_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022UserBehavior.proto\022\033cn.com.cig.adsense" +
      ".protobuf\"_\n\024MaterialBehaviorList\022G\n\020mat" +
      "erialBehavior\030\001 \003(\0132-.cn.com.cig.adsense" +
      ".protobuf.MaterialBehavior\"\244\001\n\020MaterialB" +
      "ehavior\022\022\n\nmaterialId\030\001 \001(\t\022\030\n\020impressio" +
      "nPeriod\030\002 \001(\005\022\023\n\013clickPeriod\030\003 \001(\005\022\026\n\016la" +
      "stImpression\030\004 \001(\003\022\021\n\tlastClick\030\005 \001(\003\022\021\n" +
      "\tproductId\030\006 \001(\t\022\017\n\007modelId\030\007 \001(\tB%\n\025cn." +
      "com.cig.adsense.voB\014UserBehavior"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_cn_com_cig_adsense_protobuf_MaterialBehaviorList_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_cn_com_cig_adsense_protobuf_MaterialBehaviorList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cn_com_cig_adsense_protobuf_MaterialBehaviorList_descriptor,
              new java.lang.String[] { "MaterialBehavior", });
          internal_static_cn_com_cig_adsense_protobuf_MaterialBehavior_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_cn_com_cig_adsense_protobuf_MaterialBehavior_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cn_com_cig_adsense_protobuf_MaterialBehavior_descriptor,
              new java.lang.String[] { "MaterialId", "ImpressionPeriod", "ClickPeriod", "LastImpression", "LastClick", "ProductId", "ModelId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
