
package cn.com.cig.adsense.dao.wsdl.mall;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "YiCheMallForAdvertizementSoap", targetNamespace = "http://www.yichemall.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface YiCheMallForAdvertizementSoap {


    /**
     * 获取所有KPI商品
     * 
     * @return
     *     returns cn.com.cig.adsense.externalinterface.yichemall.ReturnKpiEntity
     */
    @WebMethod(operationName = "GetKpiCarInfo", action = "http://www.yichemall.com/GetKpiCarInfo")
    @WebResult(name = "Items", targetNamespace = "http://www.yichemall.com/")
    @RequestWrapper(localName = "GetKpiCarInfo", targetNamespace = "http://www.yichemall.com/", className = "cn.com.cig.adsense.externalinterface.yichemall.GetKpiCarInfo")
    @ResponseWrapper(localName = "GetKpiCarInfoResponse", targetNamespace = "http://www.yichemall.com/", className = "cn.com.cig.adsense.externalinterface.yichemall.GetKpiCarInfoResponse")
    public ReturnKpiEntity getKpiCarInfo();

    /**
     * 获取所有上架状态的商品
     * 
     * @return
     *     returns cn.com.cig.adsense.externalinterface.yichemall.ReturnKpiEntity
     */
    @WebMethod(operationName = "GetAllCarInfoList", action = "http://www.yichemall.com/GetAllCarInfoList")
    @WebResult(name = "Items", targetNamespace = "http://www.yichemall.com/")
    @RequestWrapper(localName = "GetAllCarInfoList", targetNamespace = "http://www.yichemall.com/", className = "cn.com.cig.adsense.externalinterface.yichemall.GetAllCarInfoList")
    @ResponseWrapper(localName = "GetAllCarInfoListResponse", targetNamespace = "http://www.yichemall.com/", className = "cn.com.cig.adsense.externalinterface.yichemall.GetAllCarInfoListResponse")
    public ReturnKpiEntity getAllCarInfoList();

}
