
package cn.com.cig.adsense.dao.wsdl.mall;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "YiCheMallForAdvertizement", targetNamespace = "http://www.yichemall.com/", wsdlLocation = "http://api.yichemall.com/jzapi/YiCheMallForAdvertizement.asmx?WSDL")
public class YiCheMallForAdvertizement
    extends Service
{

    private final static URL YICHEMALLFORADVERTIZEMENT_WSDL_LOCATION;
    private final static WebServiceException YICHEMALLFORADVERTIZEMENT_EXCEPTION;
    private final static QName YICHEMALLFORADVERTIZEMENT_QNAME = new QName("http://www.yichemall.com/", "YiCheMallForAdvertizement");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://api.yichemall.com/jzapi/YiCheMallForAdvertizement.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        YICHEMALLFORADVERTIZEMENT_WSDL_LOCATION = url;
        YICHEMALLFORADVERTIZEMENT_EXCEPTION = e;
    }

    public YiCheMallForAdvertizement() {
        super(__getWsdlLocation(), YICHEMALLFORADVERTIZEMENT_QNAME);
    }

    public YiCheMallForAdvertizement(WebServiceFeature... features) {
        super(__getWsdlLocation(), YICHEMALLFORADVERTIZEMENT_QNAME, features);
    }

    public YiCheMallForAdvertizement(URL wsdlLocation) {
        super(wsdlLocation, YICHEMALLFORADVERTIZEMENT_QNAME);
    }

    public YiCheMallForAdvertizement(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, YICHEMALLFORADVERTIZEMENT_QNAME, features);
    }

    public YiCheMallForAdvertizement(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public YiCheMallForAdvertizement(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns YiCheMallForAdvertizementSoap
     */
    @WebEndpoint(name = "YiCheMallForAdvertizementSoap")
    public YiCheMallForAdvertizementSoap getYiCheMallForAdvertizementSoap() {
        return super.getPort(new QName("http://www.yichemall.com/", "YiCheMallForAdvertizementSoap"), YiCheMallForAdvertizementSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns YiCheMallForAdvertizementSoap
     */
    @WebEndpoint(name = "YiCheMallForAdvertizementSoap")
    public YiCheMallForAdvertizementSoap getYiCheMallForAdvertizementSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.yichemall.com/", "YiCheMallForAdvertizementSoap"), YiCheMallForAdvertizementSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns YiCheMallForAdvertizementSoap
     */
    @WebEndpoint(name = "YiCheMallForAdvertizementSoap12")
    public YiCheMallForAdvertizementSoap getYiCheMallForAdvertizementSoap12() {
        return super.getPort(new QName("http://www.yichemall.com/", "YiCheMallForAdvertizementSoap12"), YiCheMallForAdvertizementSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns YiCheMallForAdvertizementSoap
     */
    @WebEndpoint(name = "YiCheMallForAdvertizementSoap12")
    public YiCheMallForAdvertizementSoap getYiCheMallForAdvertizementSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.yichemall.com/", "YiCheMallForAdvertizementSoap12"), YiCheMallForAdvertizementSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (YICHEMALLFORADVERTIZEMENT_EXCEPTION!= null) {
            throw YICHEMALLFORADVERTIZEMENT_EXCEPTION;
        }
        return YICHEMALLFORADVERTIZEMENT_WSDL_LOCATION;
    }

}
